//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtrayUserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XtrayUserInterface.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率：.
        /// </summary>
        public static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接串口.
        /// </summary>
        public static string connectPort {
            get {
                return ResourceManager.GetString("connectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT密码：.
        /// </summary>
        public static string mqttPwd {
            get {
                return ResourceManager.GetString("mqttPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT用户名：.
        /// </summary>
        public static string mqttUsername {
            get {
                return ResourceManager.GetString("mqttUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他设置.
        /// </summary>
        public static string otherTabName {
            get {
                return ResourceManager.GetString("otherTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口号：.
        /// </summary>
        public static string portNumber {
            get {
                return ResourceManager.GetString("portNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收数据.
        /// </summary>
        public static string receiveData {
            get {
                return ResourceManager.GetString("receiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启系统.
        /// </summary>
        public static string resetButton {
            get {
                return ResourceManager.GetString("resetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存接收和发送数据.
        /// </summary>
        public static string saveData {
            get {
                return ResourceManager.GetString("saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索串口.
        /// </summary>
        public static string searchPort {
            get {
                return ResourceManager.GetString("searchPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送数据.
        /// </summary>
        public static string sendData {
            get {
                return ResourceManager.GetString("sendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器IP：.
        /// </summary>
        public static string serverIP {
            get {
                return ResourceManager.GetString("serverIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器名称：.
        /// </summary>
        public static string serverName {
            get {
                return ResourceManager.GetString("serverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器设置.
        /// </summary>
        public static string serverTabName {
            get {
                return ResourceManager.GetString("serverTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称重归零（请确保X-Tray上无其他物品）.
        /// </summary>
        public static string tareButton {
            get {
                return ResourceManager.GetString("tareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Tray串口设置工具.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi名称：.
        /// </summary>
        public static string wifiName {
            get {
                return ResourceManager.GetString("wifiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi密码：.
        /// </summary>
        public static string wifiPwd {
            get {
                return ResourceManager.GetString("wifiPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi设置.
        /// </summary>
        public static string wifiTabPageName {
            get {
                return ResourceManager.GetString("wifiTabPageName", resourceCulture);
            }
        }
    }
}
